# Generated by Django 5.1.2 on 2025-12-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DisplayScreen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الشاشة")),
                (
                    "token",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="رمز الوصول",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر ظهور"
                    ),
                ),
            ],
            options={
                "verbose_name": "شاشة عرض",
                "verbose_name_plural": "شاشات العرض",
            },
        ),
    ]
