# Generated by Django 5.1.2 on 2025-12-05 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="اسم المدرسة")),
                (
                    "slug",
                    models.SlugField(
                        help_text="يستخدم في الرابط، مثلا: school-1",
                        unique=True,
                        verbose_name="رابط المدرسة",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="schools/logos/",
                        verbose_name="الشعار",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="اشتراك نشط"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "مدرسة",
                "verbose_name_plural": "المدارس",
            },
        ),
        migrations.AddField(
            model_name="displayscreen",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="screens",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
    ]
