# Generated by Django 5.1.2 on 2025-12-11 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="يُستخدم داخليًا، مثل: basic, pro, enterprise",
                        unique=True,
                        verbose_name="رمز الخطة",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="اسم الخطة")),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="السعر الشهري (ر.س)",
                    ),
                ),
                (
                    "max_users",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="اتركه فارغًا لعدد غير محدود.",
                        null=True,
                        verbose_name="الحد الأقصى للمستخدمين",
                    ),
                ),
                (
                    "max_screens",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="اتركه فارغًا لعدد غير محدود.",
                        null=True,
                        verbose_name="الحد الأقصى لشاشات العرض",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="متاحة للاشتراك"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=1, verbose_name="ترتيب العرض"),
                ),
            ],
            options={
                "verbose_name": "خطة اشتراك",
                "verbose_name_plural": "خطط الاشتراك",
                "ordering": ("sort_order", "price_monthly"),
            },
        ),
        migrations.CreateModel(
            name="SchoolSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البداية")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="ملاحظات"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="core.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="core.subscriptionplan",
                        verbose_name="الخطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "اشتراك مدرسة",
                "verbose_name_plural": "اشتراكات المدارس",
                "ordering": ("-start_date", "-created_at"),
            },
        ),
    ]
