# Generated by Django 5.1.2 on 2025-12-11 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_subscriptionplan_schoolsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolsubscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.subscriptionplan",
                verbose_name="الخطة",
            ),
        ),
        migrations.AlterField(
            model_name="schoolsubscription",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
    ]
