# Generated by Django 5.1.2 on 2025-12-12 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_schoolsubscription_plan_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schoolsubscription",
            options={
                "ordering": ("-start_date", "-created_at"),
                "verbose_name": "اشتراك مدرسة (قديم)",
                "verbose_name_plural": "اشتراكات المدارس (قديمة)",
            },
        ),
    ]
