# Generated by Django 4.2.5 on 2024-07-16 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_schoolsubscription_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_schools',
            field=models.PositiveIntegerField(default=1, help_text='العدد المسموح به من المدارس في هذه الخطة.', verbose_name='الحد الأقصى للمدارس'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='school',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='core.school', verbose_name='المدرسة النشطة'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.school', verbose_name='المدارس المتاحة'),
        ),
    ]
