# Generated by Django 5.1.2 on 2025-12-14 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_schoolsubscription_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="displayscreen",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "شاشة عرض",
                "verbose_name_plural": "شاشات العرض",
            },
        ),
        migrations.AlterModelOptions(
            name="school",
            options={
                "ordering": ("name",),
                "verbose_name": "مدرسة",
                "verbose_name_plural": "المدارس",
            },
        ),
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={
                "ordering": ("sort_order", "price_monthly", "name"),
                "verbose_name": "خطة اشتراك",
                "verbose_name_plural": "خطط الاشتراك",
            },
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="school",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="active_school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_profiles",
                to="core.school",
                verbose_name="المدرسة النشطة",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="schools",
            field=models.ManyToManyField(
                blank=True,
                related_name="profiles",
                to="core.school",
                verbose_name="المدارس المرتبطة",
            ),
        ),
        migrations.AlterField(
            model_name="displayscreen",
            name="token",
            field=models.CharField(
                db_index=True,
                editable=False,
                max_length=64,
                unique=True,
                verbose_name="رمز الوصول",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="حالة تفعيل المدرسة داخل النظام (قد تكون مرتبطة بالاشتراك أو قرار إداري).",
                verbose_name="اشتراك نشط",
            ),
        ),
    ]
