# Generated by Django 5.1.2 on 2025-12-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_max_schools_and_userprofile_changes"),
    ]

    operations = [
        migrations.AddField(
            model_name="displayscreen",
            name="short_code",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=8,
                null=True,
                unique=True,
                verbose_name="رابط مختصر",
            ),
        ),
    ]
