# Generated by Django 5.1.2 on 2025-12-14 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_displayscreen_options_alter_school_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                null=True,
                blank=True,
                verbose_name="تاريخ الإنشاء",
            ),
        ),
        migrations.AddIndex(
            model_name="displayscreen",
            index=models.Index(
                fields=["school", "is_active"],
                name="core_displa_school__2dafb8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="displayscreen",
            index=models.Index(
                fields=["token"],
                name="core_displa_token_4af60a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(
                fields=["slug"],
                name="core_school_slug_e50b55_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(
                fields=["is_active"],
                name="core_school_is_acti_2e0f0f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="schoolsubscription",
            index=models.Index(
                fields=["school", "is_active"],
                name="core_school_school__867f43_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="schoolsubscription",
            index=models.Index(
                fields=["start_date"],
                name="core_school_start_d_1b6a7d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(
                fields=["code"],
                name="core_subscr_code_c027cb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(
                fields=["is_active"],
                name="core_subscr_is_acti_f08f70_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["active_school"],
                name="core_userpr_active__84c2e6_idx",
            ),
        ),
    ]
