# Generated by Django 5.1.2 on 2025-12-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_userprofile_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الإنشاء"
            ),
        ),
    ]
