# Generated by Django 5.1.2 on 2025-12-17 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_displayscreen_token_supportticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_tickets",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mobile",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="رقم الجوال"
            ),
        ),
    ]
