# Generated by Django 5.1.2 on 2025-12-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_supportticket_school_userprofile_mobile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={
                "ordering": ("sort_order", "price"),
                "verbose_name": "خطة اشتراك",
                "verbose_name_plural": "خطط الاشتراك",
            },
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="price_monthly",
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="duration_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="عدد الأيام التي تستمر فيها الباقة.",
                verbose_name="مدة الباقة (بالأيام)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="سعر الباقة (ر.س)",
            ),
        ),
    ]
