# Generated by Django 5.1.2 on 2025-12-17 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_subscriptionplan_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="duration_days",
        ),
    ]
