# Generated by Django 5.1.2 on 2025-12-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_ticketcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="displayscreen",
            name="bound_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ ربط الجهاز"
            ),
        ),
        migrations.AddField(
            model_name="displayscreen",
            name="bound_device_id",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="معرّف الجهاز المرتبط"
            ),
        ),
    ]
