# Generated by Django 5.1.2 on 2025-12-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_displayscreen_bound_at_displayscreen_bound_device_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="school_type",
            field=models.CharField(
                blank=True,
                choices=[("boys", "بنين"), ("girls", "بنات")],
                max_length=10,
                null=True,
                verbose_name="نوع المدرسة",
            ),
        ),
    ]
