# Generated by Django 5.1.2 on 2025-12-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_school_school_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="displayscreen",
            name="auto_disabled_by_limit",
            field=models.BooleanField(default=False, verbose_name="موقوف تلقائياً بسبب الحد"),
        ),
    ]
