# Generated by Django 5.1.2 on 2025-12-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_displayscreen_auto_disabled_by_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="duration_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="عند إنشاء اشتراك وترك تاريخ النهاية فارغًا: النهاية = تاريخ البداية + عدد الأيام.",
                null=True,
                verbose_name="مدة الاشتراك (بالأيام)",
            ),
        ),
    ]
