# Generated by Django 5.1.2 on 2026-03-26 01:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_subscriptionplan_duration_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="schools/logos/",
                validators=[core.models._validate_image_extension],
                verbose_name="الشعار",
            ),
        ),
    ]
