# Generated by Django 5.1.2 on 2025-10-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StandbyAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "period_index",
                    models.PositiveSmallIntegerField(verbose_name="رقم الحصة"),
                ),
                ("class_name", models.CharField(max_length=50, verbose_name="الفصل")),
                (
                    "teacher_name",
                    models.CharField(max_length=100, verbose_name="اسم المعلّم"),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=200, verbose_name="ملاحظة"),
                ),
            ],
            options={
                "verbose_name": "تكليف انتظار",
                "verbose_name_plural": "تكليفات انتظار",
                "ordering": ("-date", "period_index"),
            },
        ),
    ]
