# Generated by Django 5.1.2 on 2025-12-05 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_school_displayscreen_school"),
        ("standby", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="standbyassignment",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standby_assignments",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
    ]
