# Generated by Django 5.1.2 on 2025-12-07 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standby", "0002_standbyassignment_school"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standbyassignment",
            name="class_name",
        ),
        migrations.AddField(
            model_name="standbyassignment",
            name="classroom",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standby_assignments",
                to="schedule.schoolclass",
                verbose_name="الفصل",
            ),
        ),
    ]
