# Generated by Django 5.1.2 on 2025-12-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standby", "0003_remove_standbyassignment_class_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standbyassignment",
            name="classroom",
        ),
        migrations.AddField(
            model_name="standbyassignment",
            name="class_name",
            field=models.CharField(default="", max_length=50, verbose_name="الفصل"),
            preserve_default=False,
        ),
    ]
