# Generated by Django 5.1.2 on 2026-01-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_subscriptionplan_duration_days"),
        ("standby", "0004_remove_standbyassignment_classroom_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="standbyassignment",
            index=models.Index(
                fields=["school", "date"], name="standby_school_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="standbyassignment",
            index=models.Index(
                fields=["school", "date", "period_index"],
                name="standby_school_date_pidx",
            ),
        ),
    ]
