# Generated by Django 5.1.2 on 2025-10-24 23:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="العنوان")),
                (
                    "body",
                    models.CharField(blank=True, max_length=280, verbose_name="النص"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("urgent", "عاجل"),
                            ("warning", "تنبيه"),
                            ("info", "معلومة"),
                            ("success", "تهنئة"),
                        ],
                        default="info",
                        max_length=10,
                        verbose_name="المستوى",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="يظهر من"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ينتهي في"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
            ],
            options={
                "verbose_name": "تنبيه",
                "verbose_name_plural": "تنبيهات",
                "ordering": ("-starts_at",),
            },
        ),
        migrations.CreateModel(
            name="Excellence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teacher_name",
                    models.CharField(max_length=100, verbose_name="اسم المعلم"),
                ),
                ("reason", models.CharField(max_length=200, verbose_name="سبب التميّز")),
                (
                    "photo_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="صورة (اختياري)"
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="يظهر من"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ينتهي في"
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="أولوية العرض"
                    ),
                ),
            ],
            options={
                "verbose_name": "تميّز",
                "verbose_name_plural": "تميّز",
                "ordering": ("priority", "-start_at"),
            },
        ),
    ]
