# Generated by Django 5.1.2 on 2025-10-25 03:00

import django.core.validators
import notices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="excellence",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="صيغة مدعومة: JPG/PNG/WEBP. الحجم يُدار عبر إعدادات الخادم.",
                null=True,
                upload_to=notices.models._excellence_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    )
                ],
                verbose_name="صورة (رفع ملف)",
            ),
        ),
        migrations.AlterField(
            model_name="excellence",
            name="photo_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="رابط صورة (اختياري)"
            ),
        ),
    ]
