# Generated by Django 5.1.2 on 2025-12-09 21:12

import django.core.validators
import notices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0004_excellence_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excellence",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="الصيغ المدعومة: JPG / JPEG / PNG / WEBP.",
                null=True,
                upload_to=notices.models._excellence_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    )
                ],
                verbose_name="صورة (رفع ملف)",
            ),
        ),
    ]
