# Generated by Django 5.1.2 on 2026-01-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_subscriptionplan_duration_days"),
        ("notices", "0005_alter_excellence_photo"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["school", "is_active"], name="ann_school_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["school", "starts_at"], name="ann_school_starts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["school", "expires_at"], name="ann_school_expires_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="excellence",
            index=models.Index(
                fields=["school", "start_at"], name="exc_school_day_idx"
            ),
        ),
    ]
