# Generated by Django 5.1.2 on 2025-12-07 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "مادة",
                "verbose_name_plural": "المواد",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "معلم",
                "verbose_name_plural": "المعلمون",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("theme", models.CharField(default="default", max_length=50)),
                (
                    "timezone_name",
                    models.CharField(default="Asia/Riyadh", max_length=64),
                ),
                ("refresh_interval_sec", models.PositiveIntegerField(default=60)),
                ("standby_scroll_speed", models.FloatField(default=0.8)),
                (
                    "school",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_settings",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعداد المدرسة",
                "verbose_name_plural": "إعدادات المدرسة",
            },
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_classes",
                        to="schedule.schoolsettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "صف",
                "verbose_name_plural": "الصفوف",
                "ordering": ["name"],
                "unique_together": {("settings", "name")},
            },
        ),
        migrations.CreateModel(
            name="DaySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "الأحد"),
                            (1, "الاثنين"),
                            (2, "الثلاثاء"),
                            (3, "الأربعاء"),
                            (4, "الخميس"),
                            (5, "الجمعة"),
                            (6, "السبت"),
                        ]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("periods_count", models.PositiveSmallIntegerField(default=6)),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_schedules",
                        to="schedule.schoolsettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "جدول يوم",
                "verbose_name_plural": "جداول الأيام",
                "ordering": ("weekday",),
            },
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveSmallIntegerField()),
                ("starts_at", models.TimeField()),
                ("ends_at", models.TimeField()),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="schedule.dayschedule",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="schedule.schoolclass",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="schedule.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="schedule.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "حصة",
                "verbose_name_plural": "الحصص",
                "ordering": ("day__weekday", "index", "starts_at"),
            },
        ),
        migrations.CreateModel(
            name="Break",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(default="فسحة", max_length=50)),
                ("starts_at", models.TimeField()),
                ("duration_min", models.PositiveSmallIntegerField(default=20)),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaks",
                        to="schedule.dayschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "فسحة",
                "verbose_name_plural": "فسح",
                "ordering": ("day__weekday", "starts_at"),
                "indexes": [
                    models.Index(
                        fields=["day", "starts_at"], name="idx_break_day_start"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="dayschedule",
            index=models.Index(
                fields=["settings", "weekday"], name="idx_settings_weekday"
            ),
        ),
        migrations.AddConstraint(
            model_name="dayschedule",
            constraint=models.UniqueConstraint(
                fields=("settings", "weekday"), name="uniq_settings_weekday"
            ),
        ),
        migrations.AddIndex(
            model_name="period",
            index=models.Index(
                fields=["day", "starts_at"], name="idx_period_day_start"
            ),
        ),
        migrations.AddIndex(
            model_name="period",
            index=models.Index(fields=["day", "ends_at"], name="idx_period_day_end"),
        ),
        migrations.AddConstraint(
            model_name="period",
            constraint=models.UniqueConstraint(
                fields=("day", "index"), name="uniq_period_day_index"
            ),
        ),
    ]
