# Generated by Django 5.1.2 on 2025-10-24 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DaySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "الأحد"),
                            (1, "الاثنين"),
                            (2, "الثلاثاء"),
                            (3, "الأربعاء"),
                            (4, "الخميس"),
                            (5, "الجمعة"),
                            (6, "السبت"),
                        ],
                        verbose_name="اليوم",
                    ),
                ),
                (
                    "periods_count",
                    models.PositiveSmallIntegerField(
                        default=6, verbose_name="عدد الحصص"
                    ),
                ),
            ],
            options={
                "verbose_name": "جدول يوم",
                "verbose_name_plural": "جداول الأيام",
                "ordering": ("weekday",),
            },
        ),
        migrations.CreateModel(
            name="SchoolSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="اسم المدرسة")),
                (
                    "logo_url",
                    models.URLField(blank=True, null=True, verbose_name="رابط الشعار"),
                ),
                (
                    "theme",
                    models.CharField(
                        default="default", max_length=50, verbose_name="الثيم/اللون"
                    ),
                ),
                (
                    "timezone_name",
                    models.CharField(
                        default="Asia/Riyadh",
                        max_length=64,
                        verbose_name="المنطقة الزمنية",
                    ),
                ),
                (
                    "refresh_interval_sec",
                    models.PositiveIntegerField(
                        default=60, verbose_name="فاصل تحديث الشاشة (ث)"
                    ),
                ),
                (
                    "auto_dark_after_hour",
                    models.PositiveSmallIntegerField(
                        default=15, verbose_name="تفعيل الوضع الليلي بعد الساعة"
                    ),
                ),
            ],
            options={
                "verbose_name": "إعداد المدرسة",
                "verbose_name_plural": "إعدادات المدرسة",
            },
        ),
        migrations.CreateModel(
            name="Break",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        default="فسحة", max_length=50, verbose_name="تسمية"
                    ),
                ),
                ("starts_at", models.TimeField(verbose_name="يبدأ")),
                (
                    "duration_min",
                    models.PositiveSmallIntegerField(
                        default=20, verbose_name="المدة (دقائق)"
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaks",
                        to="schedule.dayschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "فسحة",
                "verbose_name_plural": "فسح",
                "ordering": ("day__weekday", "starts_at"),
            },
        ),
        migrations.AddField(
            model_name="dayschedule",
            name="settings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="day_schedules",
                to="schedule.schoolsettings",
            ),
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index",
                    models.PositiveSmallIntegerField(verbose_name="الترتيب (1..ن)"),
                ),
                ("starts_at", models.TimeField(verbose_name="يبدأ")),
                ("ends_at", models.TimeField(verbose_name="ينتهي")),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="schedule.dayschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "حصة",
                "verbose_name_plural": "الحصص",
                "ordering": ("day__weekday", "index"),
                "unique_together": {("day", "index")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="dayschedule",
            unique_together={("settings", "weekday")},
        ),
    ]
