# Generated by Django 5.1.2 on 2025-12-09 05:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم المادة")),
            ],
            options={
                "verbose_name": "مادة",
                "verbose_name_plural": "المواد",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم المعلم")),
            ],
            options={
                "verbose_name": "معلم",
                "verbose_name_plural": "المعلمون",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "show_home",
                    models.BooleanField(
                        default=True, verbose_name="إظهار الصفحة الرئيسية"
                    ),
                ),
                (
                    "show_settings",
                    models.BooleanField(
                        default=True, verbose_name="إظهار إعدادات المدرسة"
                    ),
                ),
                (
                    "show_change_password",
                    models.BooleanField(
                        default=True, verbose_name="إظهار تغيير كلمة المرور"
                    ),
                ),
                (
                    "show_screens",
                    models.BooleanField(default=True, verbose_name="إظهار شاشات العرض"),
                ),
                (
                    "show_days",
                    models.BooleanField(
                        default=True, verbose_name="إظهار جداول الأيام"
                    ),
                ),
                (
                    "show_announcements",
                    models.BooleanField(default=True, verbose_name="إظهار التنبيهات"),
                ),
                (
                    "show_excellence",
                    models.BooleanField(default=True, verbose_name="إظهار قسم التميز"),
                ),
                (
                    "show_standby",
                    models.BooleanField(
                        default=True, verbose_name="إظهار حصص الانتظار"
                    ),
                ),
                (
                    "show_lessons",
                    models.BooleanField(
                        default=True, verbose_name="إظهار الحصص المجدولة"
                    ),
                ),
                (
                    "show_school_data",
                    models.BooleanField(
                        default=True, verbose_name="إظهار الفصول والمواد والمعلمون"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="اسم المدرسة")),
                (
                    "logo_url",
                    models.URLField(blank=True, null=True, verbose_name="رابط الشعار"),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("default", "افتراضي"),
                            ("boys", "مدارس البنين"),
                            ("girls", "مدارس البنات"),
                        ],
                        default="default",
                        max_length=50,
                        verbose_name="الثيم/اللون",
                    ),
                ),
                (
                    "timezone_name",
                    models.CharField(
                        default="Asia/Riyadh",
                        max_length=64,
                        verbose_name="المنطقة الزمنية",
                    ),
                ),
                (
                    "refresh_interval_sec",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="عدد الثواني بين كل تحديث تلقائي للشاشة.",
                        validators=[django.core.validators.MinValueValidator(5)],
                        verbose_name="فاصل تحديث الشاشة (ثوانٍ)",
                    ),
                ),
                (
                    "standby_scroll_speed",
                    models.FloatField(
                        default=0.8,
                        help_text="سرعة تمرير قائمة حصص الانتظار (من 0.05 إلى 5.0).",
                        validators=[
                            django.core.validators.MinValueValidator(0.05),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="سرعة تمرير الانتظار",
                    ),
                ),
                (
                    "periods_scroll_speed",
                    models.FloatField(
                        default=0.5,
                        help_text="سرعة حركة تمرير جدول الحصص على الشاشة الرئيسية (من 0.05 إلى 5.0).",
                        validators=[
                            django.core.validators.MinValueValidator(0.05),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="سرعة تمرير جدول الحصص",
                    ),
                ),
                (
                    "school",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_settings",
                        to="core.school",
                        verbose_name="المدرسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعداد المدرسة",
                "verbose_name_plural": "إعدادات المدرسة",
            },
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="اسم الصف")),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_classes",
                        to="schedule.schoolsettings",
                        verbose_name="إعدادات المدرسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "صف",
                "verbose_name_plural": "الصفوف",
                "ordering": ["name"],
                "unique_together": {("settings", "name")},
            },
        ),
        migrations.CreateModel(
            name="DaySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "الأحد"),
                            (1, "الاثنين"),
                            (2, "الثلاثاء"),
                            (3, "الأربعاء"),
                            (4, "الخميس"),
                            (5, "الجمعة"),
                            (6, "السبت"),
                        ],
                        verbose_name="اليوم",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="يوم دراسي"),
                ),
                (
                    "periods_count",
                    models.PositiveSmallIntegerField(
                        default=6, verbose_name="عدد الحصص"
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_schedules",
                        to="schedule.schoolsettings",
                        verbose_name="إعدادات المدرسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "جدول يوم",
                "verbose_name_plural": "جداول الأيام",
                "ordering": ("weekday",),
            },
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index",
                    models.PositiveSmallIntegerField(verbose_name="ترتيب الحصة (1..ن)"),
                ),
                ("starts_at", models.TimeField(verbose_name="يبدأ")),
                ("ends_at", models.TimeField(verbose_name="ينتهي")),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="schedule.dayschedule",
                        verbose_name="جدول اليوم",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="schedule.schoolclass",
                        verbose_name="الصف",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="schedule.subject",
                        verbose_name="المادة",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="schedule.teacher",
                        verbose_name="المعلم",
                    ),
                ),
            ],
            options={
                "verbose_name": "حصة",
                "verbose_name_plural": "الحصص",
                "ordering": ("day__weekday", "index", "starts_at"),
            },
        ),
        migrations.CreateModel(
            name="ClassLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "الأحد"),
                            (1, "الاثنين"),
                            (2, "الثلاثاء"),
                            (3, "الأربعاء"),
                            (4, "الخميس"),
                            (5, "الجمعة"),
                            (6, "السبت"),
                        ],
                        verbose_name="اليوم",
                    ),
                ),
                (
                    "period_index",
                    models.PositiveSmallIntegerField(verbose_name="رقم الحصة"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّلة")),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_lessons",
                        to="schedule.schoolclass",
                        verbose_name="الصف",
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_lessons",
                        to="schedule.schoolsettings",
                        verbose_name="إعدادات المدرسة",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_lessons",
                        to="schedule.subject",
                        verbose_name="المادة",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_lessons",
                        to="schedule.teacher",
                        verbose_name="المعلم",
                    ),
                ),
            ],
            options={
                "verbose_name": "حصة مجدولة",
                "verbose_name_plural": "الحصص المجدولة",
                "ordering": (
                    "settings",
                    "weekday",
                    "period_index",
                    "school_class__name",
                ),
            },
        ),
        migrations.CreateModel(
            name="Break",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        default="فسحة", max_length=50, verbose_name="تسمية الفسحة"
                    ),
                ),
                ("starts_at", models.TimeField(verbose_name="يبدأ")),
                (
                    "duration_min",
                    models.PositiveSmallIntegerField(
                        default=20, verbose_name="المدة (دقائق)"
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaks",
                        to="schedule.dayschedule",
                        verbose_name="جدول اليوم",
                    ),
                ),
            ],
            options={
                "verbose_name": "فسحة",
                "verbose_name_plural": "فسح",
                "ordering": ("day__weekday", "starts_at"),
                "indexes": [
                    models.Index(
                        fields=["day", "starts_at"], name="idx_break_day_start"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="dayschedule",
            index=models.Index(
                fields=["settings", "weekday"], name="idx_settings_weekday"
            ),
        ),
        migrations.AddConstraint(
            model_name="dayschedule",
            constraint=models.UniqueConstraint(
                fields=("settings", "weekday"), name="uniq_settings_weekday"
            ),
        ),
        migrations.AddIndex(
            model_name="period",
            index=models.Index(
                fields=["day", "starts_at"], name="idx_period_day_start"
            ),
        ),
        migrations.AddIndex(
            model_name="period",
            index=models.Index(fields=["day", "ends_at"], name="idx_period_day_end"),
        ),
        migrations.AddConstraint(
            model_name="period",
            constraint=models.UniqueConstraint(
                fields=("day", "index"), name="uniq_period_day_index"
            ),
        ),
        migrations.AddIndex(
            model_name="classlesson",
            index=models.Index(
                fields=["settings", "weekday", "period_index"],
                name="idx_classlesson_lookup",
            ),
        ),
        migrations.AddConstraint(
            model_name="classlesson",
            constraint=models.UniqueConstraint(
                fields=("settings", "weekday", "period_index", "school_class"),
                name="uniq_classlesson_slot",
            ),
        ),
    ]
