# Generated by Django 5.1.2 on 2025-10-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="period",
            options={
                "ordering": ("day__weekday", "index", "starts_at"),
                "verbose_name": "حصة",
                "verbose_name_plural": "الحصص",
            },
        ),
        migrations.AlterUniqueTogether(
            name="dayschedule",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="period",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="break",
            index=models.Index(fields=["day", "starts_at"], name="idx_break_day_start"),
        ),
        migrations.AddIndex(
            model_name="dayschedule",
            index=models.Index(
                fields=["settings", "weekday"], name="idx_settings_weekday"
            ),
        ),
        migrations.AddIndex(
            model_name="period",
            index=models.Index(
                fields=["day", "starts_at"], name="idx_period_day_start"
            ),
        ),
        migrations.AddIndex(
            model_name="period",
            index=models.Index(fields=["day", "ends_at"], name="idx_period_day_end"),
        ),
        migrations.AddConstraint(
            model_name="dayschedule",
            constraint=models.UniqueConstraint(
                fields=("settings", "weekday"), name="uniq_settings_weekday"
            ),
        ),
        migrations.AddConstraint(
            model_name="period",
            constraint=models.UniqueConstraint(
                fields=("day", "index"), name="uniq_period_day_index"
            ),
        ),
    ]
