# Generated by Django 5.1.2 on 2025-12-07 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "الأحد"),
                            (1, "الاثنين"),
                            (2, "الثلاثاء"),
                            (3, "الأربعاء"),
                            (4, "الخميس"),
                            (5, "الجمعة"),
                            (6, "السبت"),
                        ]
                    ),
                ),
                ("period_index", models.PositiveSmallIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_lessons",
                        to="schedule.schoolclass",
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_lessons",
                        to="schedule.schoolsettings",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_lessons",
                        to="schedule.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_lessons",
                        to="schedule.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "حصة مجدولة",
                "verbose_name_plural": "الحصص المجدولة",
                "ordering": (
                    "settings",
                    "weekday",
                    "period_index",
                    "school_class__name",
                ),
                "indexes": [
                    models.Index(
                        fields=["settings", "weekday", "period_index"],
                        name="idx_classlesson_lookup",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("settings", "weekday", "period_index", "school_class"),
                        name="uniq_classlesson_slot",
                    )
                ],
            },
        ),
    ]
