# Generated by Django 5.1.2 on 2025-12-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_alter_period_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="standby_scroll_speed",
            field=models.FloatField(
                default=0.8,
                help_text="القيمة الافتراضية 0.8. كلما زاد الرقم زادت السرعة.",
                verbose_name="سرعة تمرير الانتظار",
            ),
        ),
    ]
