# Generated by Django 5.1.2 on 2025-12-08 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userprofile"),
        ("schedule", "0002_classlesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="break",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breaks",
                to="schedule.dayschedule",
                verbose_name="جدول اليوم",
            ),
        ),
        migrations.AlterField(
            model_name="break",
            name="duration_min",
            field=models.PositiveSmallIntegerField(
                default=20, verbose_name="المدة (دقائق)"
            ),
        ),
        migrations.AlterField(
            model_name="break",
            name="label",
            field=models.CharField(
                default="فسحة", max_length=50, verbose_name="تسمية الفسحة"
            ),
        ),
        migrations.AlterField(
            model_name="break",
            name="starts_at",
            field=models.TimeField(verbose_name="يبدأ"),
        ),
        migrations.AlterField(
            model_name="classlesson",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="مفعّلة"),
        ),
        migrations.AlterField(
            model_name="classlesson",
            name="period_index",
            field=models.PositiveSmallIntegerField(verbose_name="رقم الحصة"),
        ),
        migrations.AlterField(
            model_name="classlesson",
            name="school_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_lessons",
                to="schedule.schoolclass",
                verbose_name="الصف",
            ),
        ),
        migrations.AlterField(
            model_name="classlesson",
            name="settings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_lessons",
                to="schedule.schoolsettings",
                verbose_name="إعدادات المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="classlesson",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_lessons",
                to="schedule.subject",
                verbose_name="المادة",
            ),
        ),
        migrations.AlterField(
            model_name="classlesson",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_lessons",
                to="schedule.teacher",
                verbose_name="المعلم",
            ),
        ),
        migrations.AlterField(
            model_name="classlesson",
            name="weekday",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "الأحد"),
                    (1, "الاثنين"),
                    (2, "الثلاثاء"),
                    (3, "الأربعاء"),
                    (4, "الخميس"),
                    (5, "الجمعة"),
                    (6, "السبت"),
                ],
                verbose_name="اليوم",
            ),
        ),
        migrations.AlterField(
            model_name="dayschedule",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="يوم دراسي"),
        ),
        migrations.AlterField(
            model_name="dayschedule",
            name="periods_count",
            field=models.PositiveSmallIntegerField(default=6, verbose_name="عدد الحصص"),
        ),
        migrations.AlterField(
            model_name="dayschedule",
            name="settings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="day_schedules",
                to="schedule.schoolsettings",
                verbose_name="إعدادات المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="dayschedule",
            name="weekday",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "الأحد"),
                    (1, "الاثنين"),
                    (2, "الثلاثاء"),
                    (3, "الأربعاء"),
                    (4, "الخميس"),
                    (5, "الجمعة"),
                    (6, "السبت"),
                ],
                verbose_name="اليوم",
            ),
        ),
        migrations.AlterField(
            model_name="period",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="schedule.dayschedule",
                verbose_name="جدول اليوم",
            ),
        ),
        migrations.AlterField(
            model_name="period",
            name="ends_at",
            field=models.TimeField(verbose_name="ينتهي"),
        ),
        migrations.AlterField(
            model_name="period",
            name="index",
            field=models.PositiveSmallIntegerField(verbose_name="ترتيب الحصة (1..ن)"),
        ),
        migrations.AlterField(
            model_name="period",
            name="school_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="schedule.schoolclass",
                verbose_name="الصف",
            ),
        ),
        migrations.AlterField(
            model_name="period",
            name="starts_at",
            field=models.TimeField(verbose_name="يبدأ"),
        ),
        migrations.AlterField(
            model_name="period",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="schedule.subject",
                verbose_name="المادة",
            ),
        ),
        migrations.AlterField(
            model_name="period",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="schedule.teacher",
                verbose_name="المعلم",
            ),
        ),
        migrations.AlterField(
            model_name="schoolclass",
            name="name",
            field=models.CharField(max_length=50, verbose_name="اسم الصف"),
        ),
        migrations.AlterField(
            model_name="schoolclass",
            name="settings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="school_classes",
                to="schedule.schoolsettings",
                verbose_name="إعدادات المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="logo_url",
            field=models.URLField(blank=True, null=True, verbose_name="رابط الشعار"),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="name",
            field=models.CharField(max_length=150, verbose_name="اسم المدرسة"),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="refresh_interval_sec",
            field=models.PositiveIntegerField(
                default=60, verbose_name="فاصل تحديث الشاشة (ثوانٍ)"
            ),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="school",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_settings",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="standby_scroll_speed",
            field=models.FloatField(
                default=0.8,
                help_text="القيمة الافتراضية 0.8. كلما زاد الرقم زادت السرعة.",
                verbose_name="سرعة تمرير الانتظار",
            ),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="theme",
            field=models.CharField(
                default="default", max_length=50, verbose_name="الثيم/اللون"
            ),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="timezone_name",
            field=models.CharField(
                default="Asia/Riyadh", max_length=64, verbose_name="المنطقة الزمنية"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=100, verbose_name="اسم المادة"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="name",
            field=models.CharField(max_length=100, verbose_name="اسم المعلم"),
        ),
    ]
