# Generated by Django 5.1.2 on 2025-12-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_schoolsettings_standby_scroll_speed"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayschedule",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="يوم دراسي"),
        ),
    ]
