# Generated by Django 5.1.2 on 2025-12-12 12:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_schoolsubscription_plan_and_more"),
        ("schedule", "0003_displayscreen"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="displayscreen",
            options={
                "ordering": ("school", "name"),
                "verbose_name": "شاشة عرض",
                "verbose_name_plural": "شاشات العرض",
            },
        ),
        migrations.AlterModelOptions(
            name="schoolclass",
            options={
                "ordering": ("name",),
                "verbose_name": "صف",
                "verbose_name_plural": "الصفوف",
            },
        ),
        migrations.AlterModelOptions(
            name="schoolsettings",
            options={
                "ordering": ("name",),
                "verbose_name": "إعداد المدرسة",
                "verbose_name_plural": "إعدادات المدرسة",
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={
                "ordering": ("name",),
                "verbose_name": "مادة",
                "verbose_name_plural": "المواد",
            },
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={
                "ordering": ("name",),
                "verbose_name": "معلم",
                "verbose_name_plural": "المعلمون",
            },
        ),
        migrations.RemoveConstraint(
            model_name="classlesson",
            name="uniq_classlesson_slot",
        ),
        migrations.RemoveConstraint(
            model_name="dayschedule",
            name="uniq_settings_weekday",
        ),
        migrations.RemoveConstraint(
            model_name="period",
            name="uniq_period_day_index",
        ),
        migrations.RemoveConstraint(
            model_name="subject",
            name="uniq_subject_per_school",
        ),
        migrations.RemoveConstraint(
            model_name="teacher",
            name="uniq_teacher_per_school",
        ),
        migrations.RenameIndex(
            model_name="break",
            new_name="ix_br_day_st",
            old_name="idx_break_day_start",
        ),
        migrations.RenameIndex(
            model_name="classlesson",
            new_name="ix_cl_lookup",
            old_name="idx_classlesson_lookup",
        ),
        migrations.RenameIndex(
            model_name="dayschedule",
            new_name="ix_ds_set_wd",
            old_name="idx_settings_weekday",
        ),
        migrations.RenameIndex(
            model_name="period",
            new_name="ix_pr_day_st",
            old_name="idx_period_day_start",
        ),
        migrations.RenameIndex(
            model_name="period",
            new_name="ix_pr_day_en",
            old_name="idx_period_day_end",
        ),
        migrations.AlterUniqueTogether(
            name="schoolclass",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="break",
            name="duration_min",
            field=models.PositiveSmallIntegerField(
                default=20,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(240),
                ],
                verbose_name="المدة (دقائق)",
            ),
        ),
        migrations.AlterField(
            model_name="classlesson",
            name="period_index",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="رقم الحصة",
            ),
        ),
        migrations.AlterField(
            model_name="dayschedule",
            name="periods_count",
            field=models.PositiveSmallIntegerField(
                default=6,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="عدد الحصص",
            ),
        ),
        migrations.AlterField(
            model_name="displayscreen",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="displayscreen",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="مفعلة"),
        ),
        migrations.AlterField(
            model_name="displayscreen",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="آخر اتصال"),
        ),
        migrations.AlterField(
            model_name="displayscreen",
            name="name",
            field=models.CharField(max_length=100, verbose_name="اسم الشاشة"),
        ),
        migrations.AlterField(
            model_name="displayscreen",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="display_screens",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="displayscreen",
            name="token",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Secure display token (64-hex).",
                max_length=64,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="التوكن يجب أن يكون 64 حرفًا (hex) مثل SHA256.",
                        regex="^[0-9a-fA-F]{64}$",
                    )
                ],
                verbose_name="توكن الشاشة",
            ),
        ),
        migrations.AlterField(
            model_name="period",
            name="index",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="ترتيب الحصة (1..ن)",
            ),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="periods_scroll_speed",
            field=models.FloatField(
                default=0.5,
                help_text="سرعة تمرير جدول الحصص (من 0.05 إلى 5.0).",
                validators=[
                    django.core.validators.MinValueValidator(0.05),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="سرعة تمرير جدول الحصص",
            ),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="theme",
            field=models.CharField(
                choices=[
                    ("default", "افتراضي"),
                    ("boys", "مدارس البنين"),
                    ("girls", "مدارس البنات"),
                ],
                default="default",
                max_length=20,
                verbose_name="الثيم/اللون",
            ),
        ),
        migrations.AddIndex(
            model_name="displayscreen",
            index=models.Index(fields=["token"], name="ix_ds_token"),
        ),
        migrations.AddIndex(
            model_name="displayscreen",
            index=models.Index(fields=["school", "is_active"], name="ix_ds_sch_act"),
        ),
        migrations.AddIndex(
            model_name="schoolclass",
            index=models.Index(fields=["settings", "name"], name="ix_sc_set_nm"),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["school", "name"], name="ix_sub_sch_nm"),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(fields=["school", "name"], name="ix_tch_sch_nm"),
        ),
        migrations.AddConstraint(
            model_name="classlesson",
            constraint=models.UniqueConstraint(
                fields=("settings", "weekday", "period_index", "school_class"),
                name="uq_cl_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="dayschedule",
            constraint=models.UniqueConstraint(
                fields=("settings", "weekday"), name="uq_ds_set_wd"
            ),
        ),
        migrations.AddConstraint(
            model_name="period",
            constraint=models.UniqueConstraint(
                fields=("day", "index"), name="uq_pr_day_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.UniqueConstraint(
                fields=("settings", "name"), name="uq_sc_set_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("school", "name"), name="uq_sub_sch_nm"
            ),
        ),
        migrations.AddConstraint(
            model_name="teacher",
            constraint=models.UniqueConstraint(
                fields=("school", "name"), name="uq_tch_sch_nm"
            ),
        ),
    ]
