# Generated by Django 5.1.2 on 2025-12-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_alter_break_day_alter_break_duration_min_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="periods_scroll_speed",
            field=models.FloatField(
                default=0.5,
                help_text="سرعة حركة تمرير جدول الحصص على الشاشة الرئيسية. 0.1 بطيء جداً — 1.0 سريع.",
                verbose_name="سرعة تمرير جدول الحصص",
            ),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="refresh_interval_sec",
            field=models.PositiveIntegerField(
                default=60,
                help_text="عدد الثواني بين كل تحديث تلقائي للشاشة.",
                verbose_name="فاصل تحديث الشاشة (ثوانٍ)",
            ),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="standby_scroll_speed",
            field=models.FloatField(
                default=0.8,
                help_text="سرعة تمرير قائمة حصص الانتظار. القيمة الافتراضية 0.8. كلما زادت السرعة زادت سرعة الحركة.",
                verbose_name="سرعة تمرير الانتظار",
            ),
        ),
    ]
