# Generated by Django 5.1.2 on 2025-12-12 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_schoolsubscription_plan_and_more"),
        ("schedule", "0004_alter_displayscreen_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dayschedule",
            name="uq_ds_set_wd",
        ),
        migrations.RemoveConstraint(
            model_name="period",
            name="uq_pr_day_idx",
        ),
        migrations.RemoveConstraint(
            model_name="subject",
            name="uq_sub_sch_nm",
        ),
        migrations.RemoveConstraint(
            model_name="teacher",
            name="uq_tch_sch_nm",
        ),
        migrations.RenameIndex(
            model_name="break",
            new_name="ix_break_start",
            old_name="ix_br_day_st",
        ),
        migrations.RenameIndex(
            model_name="dayschedule",
            new_name="ix_ds_set_day",
            old_name="ix_ds_set_wd",
        ),
        migrations.RenameIndex(
            model_name="displayscreen",
            new_name="ix_disp_token",
            old_name="ix_ds_token",
        ),
        migrations.RenameIndex(
            model_name="displayscreen",
            new_name="ix_disp_active",
            old_name="ix_ds_sch_act",
        ),
        migrations.RenameIndex(
            model_name="period",
            new_name="ix_period_start",
            old_name="ix_pr_day_st",
        ),
        migrations.RenameIndex(
            model_name="period",
            new_name="ix_period_end",
            old_name="ix_pr_day_en",
        ),
        migrations.RenameIndex(
            model_name="schoolclass",
            new_name="ix_sc_set_name",
            old_name="ix_sc_set_nm",
        ),
        migrations.RenameIndex(
            model_name="subject",
            new_name="ix_subj_school",
            old_name="ix_sub_sch_nm",
        ),
        migrations.RenameIndex(
            model_name="teacher",
            new_name="ix_teacher_school",
            old_name="ix_tch_sch_nm",
        ),
        migrations.AlterField(
            model_name="displayscreen",
            name="token",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Secure display token (64-hex).",
                max_length=64,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="التوكن يجب أن يكون 64 حرفًا (hex) مثل SHA256.",
                        regex="^[0-9a-fA-F]{64}$",
                    )
                ],
                verbose_name="توكن الشاشة",
            ),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="periods_scroll_speed",
            field=models.FloatField(
                default=0.5,
                validators=[
                    django.core.validators.MinValueValidator(0.05),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="سرعة تمرير جدول الحصص",
            ),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="standby_scroll_speed",
            field=models.FloatField(
                default=0.8,
                validators=[
                    django.core.validators.MinValueValidator(0.05),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="سرعة تمرير الانتظار",
            ),
        ),
        migrations.AddConstraint(
            model_name="dayschedule",
            constraint=models.UniqueConstraint(
                fields=("settings", "weekday"), name="uq_ds_set_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="period",
            constraint=models.UniqueConstraint(
                fields=("day", "index"), name="uq_period_day_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("school", "name"), name="uq_subj_school"
            ),
        ),
        migrations.AddConstraint(
            model_name="teacher",
            constraint=models.UniqueConstraint(
                fields=("school", "name"), name="uq_teacher_school"
            ),
        ),
    ]
