# Generated by Django 5.1.2 on 2025-12-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0004_dayschedule_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schoolsettings",
            name="auto_dark_after_hour",
        ),
    ]
