# Generated by Django 5.1.2 on 2025-12-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0004_schoolsettings_periods_scroll_speed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="show_excellence",
            field=models.BooleanField(
                default=True,
                help_text="إظهار أو إخفاء قسم التميز في المنصة لهذه المدرسة.",
                verbose_name="إظهار قسم التميز",
            ),
        ),
    ]
