# Generated by Django 5.1.2 on 2025-12-05 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_school_displayscreen_school"),
        ("schedule", "0005_remove_schoolsettings_auto_dark_after_hour"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="school",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_settings",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
    ]
