# Generated by Django 5.1.2 on 2025-12-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0005_schoolsettings_show_excellence"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="show_announcements",
            field=models.BooleanField(default=True, verbose_name="إظهار التنبيهات"),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="show_change_password",
            field=models.BooleanField(
                default=True, verbose_name="إظهار تغيير كلمة المرور"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="show_days",
            field=models.BooleanField(default=True, verbose_name="إظهار جداول الأيام"),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="show_home",
            field=models.BooleanField(
                default=True, verbose_name="إظهار الصفحة الرئيسية"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="show_lessons",
            field=models.BooleanField(
                default=True, verbose_name="إظهار الحصص المجدولة"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="show_school_data",
            field=models.BooleanField(
                default=True, verbose_name="إظهار الفصول والمواد والمعلمون"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="show_screens",
            field=models.BooleanField(default=True, verbose_name="إظهار شاشات العرض"),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="show_settings",
            field=models.BooleanField(
                default=True, verbose_name="إظهار إعدادات المدرسة"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="show_standby",
            field=models.BooleanField(default=True, verbose_name="إظهار حصص الانتظار"),
        ),
    ]
