# Generated by Django 5.1.2 on 2025-12-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_schoolsubscription_plan_and_more"),
        ("schedule", "0005_remove_dayschedule_uq_ds_set_wd_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dayschedule",
            name="uq_ds_set_day",
        ),
        migrations.RemoveConstraint(
            model_name="period",
            name="uq_period_day_idx",
        ),
        migrations.RemoveConstraint(
            model_name="schoolclass",
            name="uq_sc_set_name",
        ),
        migrations.RemoveConstraint(
            model_name="subject",
            name="uq_subj_school",
        ),
        migrations.RemoveConstraint(
            model_name="teacher",
            name="uq_teacher_school",
        ),
        migrations.RenameIndex(
            model_name="break",
            new_name="ix_b_day_st",
            old_name="ix_break_start",
        ),
        migrations.RenameIndex(
            model_name="dayschedule",
            new_name="ix_ds_set_wd",
            old_name="ix_ds_set_day",
        ),
        migrations.RenameIndex(
            model_name="displayscreen",
            new_name="ix_ds_token",
            old_name="ix_disp_token",
        ),
        migrations.RenameIndex(
            model_name="displayscreen",
            new_name="ix_ds_s_act",
            old_name="ix_disp_active",
        ),
        migrations.RenameIndex(
            model_name="period",
            new_name="ix_p_day_st",
            old_name="ix_period_start",
        ),
        migrations.RenameIndex(
            model_name="period",
            new_name="ix_p_day_en",
            old_name="ix_period_end",
        ),
        migrations.RenameIndex(
            model_name="schoolclass",
            new_name="ix_sc_set_nm",
            old_name="ix_sc_set_name",
        ),
        migrations.RenameIndex(
            model_name="subject",
            new_name="ix_sub_sch_nm",
            old_name="ix_subj_school",
        ),
        migrations.RenameIndex(
            model_name="teacher",
            new_name="ix_tch_sch_nm",
            old_name="ix_teacher_school",
        ),
        migrations.AddConstraint(
            model_name="dayschedule",
            constraint=models.UniqueConstraint(
                fields=("settings", "weekday"), name="uq_ds_set_wd"
            ),
        ),
        migrations.AddConstraint(
            model_name="period",
            constraint=models.UniqueConstraint(
                fields=("day", "index"), name="uq_p_day_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.UniqueConstraint(
                fields=("settings", "name"), name="uq_sc_set_nm"
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("school", "name"), name="uq_sub_sch_nm"
            ),
        ),
        migrations.AddConstraint(
            model_name="teacher",
            constraint=models.UniqueConstraint(
                fields=("school", "name"), name="uq_tch_sch_nm"
            ),
        ),
    ]
