# Generated by Django 5.1.2 on 2025-12-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0006_remove_dayschedule_uq_ds_set_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classlesson",
            name="weekday",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "الاثنين"),
                    (1, "الثلاثاء"),
                    (2, "الأربعاء"),
                    (3, "الخميس"),
                    (4, "الجمعة"),
                    (5, "السبت"),
                    (6, "الأحد"),
                ],
                verbose_name="اليوم",
            ),
        ),
        migrations.AlterField(
            model_name="dayschedule",
            name="weekday",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "الاثنين"),
                    (1, "الثلاثاء"),
                    (2, "الأربعاء"),
                    (3, "الخميس"),
                    (4, "الجمعة"),
                    (5, "السبت"),
                    (6, "الأحد"),
                ],
                verbose_name="اليوم",
            ),
        ),
    ]
