# Generated by Django 5.1.2 on 2025-12-08 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0006_schoolsettings_show_announcements_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolsettings",
            name="periods_scroll_speed",
            field=models.FloatField(
                default=0.5,
                help_text="سرعة حركة تمرير جدول الحصص على الشاشة الرئيسية.",
                validators=[
                    django.core.validators.MinValueValidator(0.05),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="سرعة تمرير جدول الحصص",
            ),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="show_excellence",
            field=models.BooleanField(default=True, verbose_name="إظهار قسم التميز"),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="standby_scroll_speed",
            field=models.FloatField(
                default=0.8,
                help_text="سرعة تمرير قائمة حصص الانتظار.",
                validators=[
                    django.core.validators.MinValueValidator(0.05),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="سرعة تمرير الانتظار",
            ),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="theme",
            field=models.CharField(
                choices=[
                    ("default", "افتراضي"),
                    ("boys", "مدارس البنين"),
                    ("girls", "مدارس البنات"),
                ],
                default="default",
                max_length=50,
                verbose_name="الثيم/اللون",
            ),
        ),
    ]
