# Generated by Django 5.1.2 on 2025-12-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0007_alter_classlesson_weekday_alter_dayschedule_weekday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classlesson",
            name="weekday",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "الاثنين"),
                    (2, "الثلاثاء"),
                    (3, "الأربعاء"),
                    (4, "الخميس"),
                    (5, "الجمعة"),
                    (6, "السبت"),
                    (7, "الأحد"),
                ],
                verbose_name="اليوم",
            ),
        ),
        migrations.AlterField(
            model_name="dayschedule",
            name="weekday",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "الاثنين"),
                    (2, "الثلاثاء"),
                    (3, "الأربعاء"),
                    (4, "الخميس"),
                    (5, "الجمعة"),
                    (6, "السبت"),
                    (7, "الأحد"),
                ],
                verbose_name="اليوم",
            ),
        ),
    ]
