# Generated by Django 5.1.2 on 2025-12-08 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0007_alter_schoolsettings_periods_scroll_speed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolsettings",
            name="periods_scroll_speed",
            field=models.FloatField(
                default=0.5,
                help_text="سرعة حركة تمرير جدول الحصص على الشاشة الرئيسية (من 0.05 إلى 5.0).",
                validators=[
                    django.core.validators.MinValueValidator(0.05),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="سرعة تمرير جدول الحصص",
            ),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="refresh_interval_sec",
            field=models.PositiveIntegerField(
                default=60,
                help_text="عدد الثواني بين كل تحديث تلقائي للشاشة.",
                validators=[django.core.validators.MinValueValidator(5)],
                verbose_name="فاصل تحديث الشاشة (ثوانٍ)",
            ),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="standby_scroll_speed",
            field=models.FloatField(
                default=0.8,
                help_text="سرعة تمرير قائمة حصص الانتظار (من 0.05 إلى 5.0).",
                validators=[
                    django.core.validators.MinValueValidator(0.05),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="سرعة تمرير الانتظار",
            ),
        ),
    ]
