# Generated by Django 5.1.2 on 2025-12-12 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0008_alter_classlesson_weekday_alter_dayschedule_weekday"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DisplayScreen",
        ),
    ]
