# Generated by Django 5.1.2 on 2025-12-13 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0010_alter_period_school_class_alter_period_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="period",
            name="school_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="schedule.schoolclass",
                verbose_name="الصف",
            ),
        ),
        migrations.AlterField(
            model_name="period",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="schedule.subject",
                verbose_name="المادة",
            ),
        ),
        migrations.AlterField(
            model_name="period",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="schedule.teacher",
                verbose_name="المعلم",
            ),
        ),
    ]
