# Generated by GitHub Copilot

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0011_alter_period_school_class_alter_period_subject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="display_accent_color",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=7,
                verbose_name="لون شاشة العرض (اختياري)",
                help_text="اختياري: اختر لوناً رئيسياً لشاشة العرض. اتركه فارغاً لاستخدام ألوان الثيم.",
                validators=[
                    django.core.validators.RegexValidator(
                        regex=r"^#[0-9A-Fa-f]{6}$",
                        message="أدخل لونًا بصيغة HEX مثل: #22C55E",
                    )
                ],
            ),
        ),
    ]
