# Generated by Django 5.1.2 on 2026-01-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0012_schoolsettings_display_accent_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolsettings",
            name="theme",
            field=models.CharField(
                choices=[
                    ("indigo", "أزرق/نيلي"),
                    ("emerald", "أخضر"),
                    ("rose", "وردي"),
                    ("cyan", "سماوي"),
                    ("amber", "أصفر"),
                    ("orange", "برتقالي"),
                    ("violet", "بنفسجي"),
                    ("default", "افتراضي (قديم)"),
                    ("boys", "مدارس البنين (قديم)"),
                    ("girls", "مدارس البنات (قديم)"),
                ],
                default="default",
                max_length=20,
                verbose_name="الثيم/اللون",
            ),
        ),
    ]
