# Generated by GitHub Copilot on 2026-01-21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0013_alter_schoolsettings_theme"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="featured_panel",
            field=models.CharField(
                choices=[("excellence", "لوحة الشرف"), ("duty", "لوحة الإشراف والمناوبة")],
                default="excellence",
                help_text="يحدد محتوى الكرت المميز في شاشة العرض لجميع شاشات المدرسة.",
                max_length=20,
                verbose_name="الكرت المميز في شاشة العرض",
            ),
        ),
        migrations.CreateModel(
            name="DutyAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(default=django.utils.timezone.localdate, verbose_name="التاريخ")),
                ("teacher_name", models.CharField(max_length=100, verbose_name="اسم المعلم/ـة")),
                ("duty_type", models.CharField(choices=[("supervision", "إشراف"), ("duty", "مناوبة")], max_length=20, verbose_name="النوع")),
                ("location", models.CharField(blank=True, max_length=120, verbose_name="المكان (اختياري)")),
                ("priority", models.PositiveSmallIntegerField(default=10, verbose_name="ترتيب العرض")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_assignments",
                        to="core.school",
                        verbose_name="المدرسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إشراف/مناوبة",
                "verbose_name_plural": "الإشراف والمناوبة",
                "ordering": ("date", "priority", "-id"),
            },
        ),
        migrations.AddIndex(
            model_name="dutyassignment",
            index=models.Index(fields=["school", "date"], name="duty_school_date_idx"),
        ),
        migrations.AddIndex(
            model_name="dutyassignment",
            index=models.Index(fields=["school", "date", "duty_type"], name="duty_school_date_type"),
        ),
    ]
