# Generated by Django 5.1.2 on 2026-02-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0015_schoolsettings_schedule_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="test_mode_weekday_override",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "الاثنين"),
                    (2, "الثلاثاء"),
                    (3, "الأربعاء"),
                    (4, "الخميس"),
                    (5, "الجمعة"),
                    (6, "السبت"),
                    (7, "الأحد"),
                ],
                help_text="للسوبر أدمن فقط: لتشغيل الشاشة في يوم إجازة للاختبار، حدد رقم اليوم المراد محاكاته (مثلاً: الأحد). سيعرض النظام جدول ذلك اليوم حتى في أيام الإجازة. اتركه فارغاً لإلغاء المحاكاة.",
                null=True,
                verbose_name="وضع الاختبار: محاكاة يوم",
            ),
        ),
    ]
