# Generated by Django 5.1.2 on 2026-04-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0017_fix_weekday_zero_to_sunday7"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="display_after_badge",
            field=models.CharField(
                blank=True,
                default="أحسنتم",
                help_text="تظهر كشارة صغيرة أعلى بطاقة الحالة بعد انتهاء اليوم الدراسي.",
                max_length=40,
                verbose_name="شارة الحالة بعد انتهاء الدوام",
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="display_after_title",
            field=models.CharField(
                blank=True,
                default="أحسنتم اليوم، ونلقاكم غدا بإذن الله",
                help_text="يظهر كنص رئيسي في شاشة العرض بعد انتهاء آخر حصة.",
                max_length=150,
                verbose_name="عنوان الشاشة بعد انتهاء الدوام",
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="display_before_badge",
            field=models.CharField(
                blank=True,
                default="أهلا بكم",
                help_text="تظهر كشارة صغيرة أعلى بطاقة الحالة قبل بداية اليوم الدراسي.",
                max_length=40,
                verbose_name="شارة الحالة قبل بداية الدوام",
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="display_before_title",
            field=models.CharField(
                blank=True,
                default="استعدوا لبداية يوم دراسي جميل",
                help_text="يظهر كنص رئيسي في شاشة العرض قبل بداية أول حصة.",
                max_length=150,
                verbose_name="عنوان الشاشة قبل بداية الدوام",
            ),
        ),
    ]
