# Generated by Django 5.1.2 on 2026-04-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0018_schoolsettings_display_after_badge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="display_after_holiday_badge",
            field=models.CharField(
                blank=True,
                default="إجازة",
                help_text="تظهر كشارة صغيرة بعد انتهاء الدوام عندما لا يكون اليوم التالي يومًا دراسيًا.",
                max_length=40,
                verbose_name="شارة الحالة بعد الدوام إذا كان الغد إجازة",
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="display_after_holiday_title",
            field=models.CharField(
                blank=True,
                default="أحسنتم اليوم، نتمنى لكم إجازة سعيدة",
                help_text="يظهر بعد انتهاء الدوام عندما لا يكون اليوم التالي يومًا دراسيًا.",
                max_length=150,
                verbose_name="عنوان الشاشة بعد الدوام إذا كان الغد إجازة",
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="display_holiday_badge",
            field=models.CharField(
                blank=True,
                default="إجازة",
                help_text="تظهر كشارة صغيرة أعلى بطاقة الحالة عندما يكون اليوم إجازة.",
                max_length=40,
                verbose_name="شارة الحالة في يوم الإجازة",
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="display_holiday_title",
            field=models.CharField(
                blank=True,
                default="اليوم إجازة، نتمنى لكم وقتًا سعيدًا",
                help_text="يظهر كنص رئيسي على الشاشة عندما يكون اليوم إجازة.",
                max_length=150,
                verbose_name="عنوان الشاشة في يوم الإجازة",
            ),
        ),
    ]
