# Generated by Django 5.1.2 on 2025-12-11 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0005_alter_schoolsubscription_plan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "starts_at",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="بداية الاشتراك",
                    ),
                ),
                (
                    "ends_at",
                    models.DateField(
                        blank=True,
                        help_text="اتركه فارغًا ليكون مفتوح المدة.",
                        null=True,
                        verbose_name="نهاية الاشتراك",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الإعداد"),
                            ("active", "سارية"),
                            ("expired", "منتهية"),
                            ("cancelled", "ملغاة"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="core.subscriptionplan",
                        verbose_name="الخطة",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="core.school",
                        verbose_name="المدرسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "اشتراك مدرسة",
                "verbose_name_plural": "اشتراكات المدارس",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "plan", "starts_at"),
                        name="uniq_school_plan_start",
                    )
                ],
            },
        ),
    ]
