# Generated by Django 5.1.2 on 2025-12-21 23:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionScreenAddon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "screens_added",
                    models.PositiveIntegerField(
                        help_text="عدد الشاشات الإضافية المطلوبة لهذه الفترة.",
                        verbose_name="عدد الشاشات المضافة",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="سعر الشاشة الإضافية (ر.س)",
                    ),
                ),
                (
                    "proration_factor",
                    models.DecimalField(
                        decimal_places=5,
                        default=Decimal("1.0"),
                        help_text="1.0 = كامل المدة. يتم حسابه تلقائيًا عند الحفظ إذا كان للمدة نهاية.",
                        max_digits=6,
                        verbose_name="معامل الاحتساب النسبي",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="يتم حسابه تلقائيًا: screens_added × unit_price × proration_factor.",
                        max_digits=10,
                        verbose_name="الإجمالي (ر.س)",
                    ),
                ),
                (
                    "starts_at",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="بداية الإضافة",
                    ),
                ),
                (
                    "ends_at",
                    models.DateField(
                        blank=True,
                        help_text="افتراضيًا تُضبط على نهاية الاشتراك إن وُجدت.",
                        null=True,
                        verbose_name="نهاية الإضافة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "بانتظار الدفع"),
                            ("paid", "مدفوع"),
                            ("cancelled", "ملغي"),
                            ("refunded", "مُسترد"),
                        ],
                        default="paid",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screen_addons",
                        to="subscriptions.schoolsubscription",
                        verbose_name="الاشتراك",
                    ),
                ),
            ],
            options={
                "verbose_name": "زيادة شاشات",
                "verbose_name_plural": "زيادات الشاشات",
                "ordering": ("-created_at",),
            },
        ),
    ]
