# Generated by Django 5.1.2 on 2025-12-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_subscriptionscreenaddon"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionscreenaddon",
            name="bundle_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="يُستخدم مع (يدوي مبلغ إجمالي) أو يتم تعبئته تلقائيًا في (تلقائي شرائح).",
                max_digits=10,
                verbose_name="سعر الإضافة للفترة (ر.س)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionscreenaddon",
            name="pricing_strategy",
            field=models.CharField(
                choices=[
                    ("auto_bundle", "تلقائي (شرائح)"),
                    ("manual_bundle", "يدوي (مبلغ إجمالي)"),
                    ("manual_per_screen", "يدوي (سعر لكل شاشة)"),
                ],
                default="auto_bundle",
                help_text="التلقائي: 1=25،2=40،3=55 وفوق 3 +15 لكل شاشة. السنوي×10، نصف سنوي×5.",
                max_length=30,
                verbose_name="طريقة التسعير",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionscreenaddon",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="سعر للشاشة (ر.س)",
            ),
        ),
    ]
