# Generated by Django 5.1.2 on 2025-12-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_subscriptionscreenaddon_bundle_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionscreenaddon",
            name="pricing_cycle",
            field=models.CharField(
                choices=[
                    ("inherit", "حسب الاشتراك"),
                    ("monthly", "شهري"),
                    ("semiannual", "نصف سنوي"),
                    ("annual", "سنوي"),
                ],
                default="inherit",
                help_text="مثال: اشتراك سنوي لكن إضافة لمدة شهر → اختر (شهري) وحدد مدة 30 يوم.",
                max_length=20,
                verbose_name="دورة تسعير الإضافة",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionscreenaddon",
            name="validity_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="اختياري: لو حددتها ستصبح نهاية الإضافة = البداية + (المدة-1). مثال شهر: 30 يوم.",
                null=True,
                verbose_name="مدة الصلاحية بالأيام",
            ),
        ),
    ]
