# Generated by Django 5.1.2 on 2026-01-11 23:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_subscriptionplan_duration_days"),
        ("subscriptions", "0004_subscriptionscreenaddon_pricing_cycle_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("renewal", "طلب تجديد"), ("new", "طلب اشتراك جديد")],
                        max_length=20,
                        verbose_name="نوع الطلب",
                    ),
                ),
                (
                    "requested_starts_at",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="تاريخ بدء التفعيل المطلوب",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="مبلغ التحويل (ر.س)",
                    ),
                ),
                (
                    "receipt_image",
                    models.ImageField(
                        upload_to="receipts/subscription_requests/%Y/%m",
                        verbose_name="إيصال التحويل (صورة)",
                    ),
                ),
                (
                    "transfer_note",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="ملاحظة العميل",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "مرسلة"),
                            ("under_review", "قيد المراجعة"),
                            ("approved", "معتمدة"),
                            ("rejected", "مرفوضة"),
                        ],
                        default="submitted",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(
                        blank=True, default="", verbose_name="ملاحظة الإدارة"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ المراجعة"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "approved_subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_from_requests",
                        to="subscriptions.schoolsubscription",
                        verbose_name="الاشتراك المُنشأ",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_subscription_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أُنشئ بواسطة",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription_requests",
                        to="core.subscriptionplan",
                        verbose_name="الخطة المطلوبة",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_subscription_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تمت المراجعة بواسطة",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_requests",
                        to="core.school",
                        verbose_name="المدرسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب اشتراك/تجديد",
                "verbose_name_plural": "طلبات الاشتراك/التجديد",
                "ordering": ("-created_at",),
            },
        ),
    ]
