# Generated by Django 5.1.2 on 2026-01-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_subscriptionrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionrequest",
            name="receipt_image",
            field=models.ImageField(
                max_length=500,
                upload_to="receipts/subscription_requests/%Y/%m",
                verbose_name="إيصال التحويل (صورة)",
            ),
        ),
    ]
