# Generated by Django 5.1.2 on 2026-01-20 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_subscriptionplan_duration_days"),
        ("subscriptions", "0006_alter_subscriptionrequest_receipt_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPaymentOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="المبلغ (ر.س)",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "تحويل"),
                            ("payment_link", "رابط دفع"),
                            ("tamara", "تمارا"),
                        ],
                        max_length=20,
                        verbose_name="طريقة الدفع",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("admin_manual", "إضافة يدوية"),
                            ("request", "طلب اشتراك"),
                        ],
                        default="admin_manual",
                        max_length=20,
                        verbose_name="مصدر العملية",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="ملاحظة"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ العملية"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_subscription_payment_operations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تمت بواسطة",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_operations",
                        to="core.subscriptionplan",
                        verbose_name="الخطة",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_payment_operations",
                        to="core.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_operations",
                        to="subscriptions.schoolsubscription",
                        verbose_name="الاشتراك",
                    ),
                ),
            ],
            options={
                "verbose_name": "عملية دفع اشتراك",
                "verbose_name_plural": "عمليات دفع الاشتراكات",
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
