# Generated by Django 5.1.2 on 2026-01-20 21:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_subscriptionplan_duration_days"),
        ("subscriptions", "0007_subscriptionpaymentoperation"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        editable=False,
                        max_length=40,
                        unique=True,
                        verbose_name="رقم الفاتورة",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الإصدار"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("SAR", "ر.س")],
                        default="SAR",
                        max_length=3,
                        verbose_name="العملة",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="المبلغ (ر.س)",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "تحويل"),
                            ("payment_link", "رابط دفع"),
                            ("tamara", "تمارا"),
                        ],
                        max_length=20,
                        verbose_name="طريقة الدفع",
                    ),
                ),
                (
                    "seller_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="الطرف الأول (المنصة)",
                    ),
                ),
                (
                    "buyer_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="الطرف الثاني (المدرسة)",
                    ),
                ),
                (
                    "html_snapshot",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="يُحفظ HTML النهائي للفاتورة لضمان ثباتها حتى لو تغيّر تصميم القالب لاحقًا.",
                        verbose_name="نسخة HTML",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "operation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="subscriptions.subscriptionpaymentoperation",
                        verbose_name="عملية الدفع",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription_invoices",
                        to="core.subscriptionplan",
                        verbose_name="الخطة",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_invoices",
                        to="core.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="subscriptions.schoolsubscription",
                        verbose_name="الاشتراك",
                    ),
                ),
            ],
            options={
                "verbose_name": "فاتورة اشتراك",
                "verbose_name_plural": "فواتير الاشتراكات",
                "ordering": ("-issued_at", "-id"),
            },
        ),
    ]
