# Generated by Django 5.1.2 on 2026-01-20 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_subscriptionplan_duration_days"),
        ("subscriptions", "0008_subscriptioninvoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptioninvoice",
            name="operation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice",
                to="subscriptions.subscriptionpaymentoperation",
                verbose_name="عملية الدفع",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptioninvoice",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscription_invoices",
                to="core.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptioninvoice",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="subscriptions.schoolsubscription",
                verbose_name="الاشتراك",
            ),
        ),
    ]
