# Generated by Django 5.1.2 on 2026-03-26 01:48

import subscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0009_alter_subscriptioninvoice_operation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionrequest",
            name="receipt_image",
            field=models.ImageField(
                max_length=500,
                upload_to="receipts/subscription_requests/%Y/%m",
                validators=[subscriptions.models._validate_receipt_extension],
                verbose_name="إيصال التحويل (صورة)",
            ),
        ),
    ]
